# Generated by Django 4.0.2 on 2022-02-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_shoppingcartitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
